In [5]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
a1=np.array([1,2,3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a1.dtype

dtype('int32')

In [6]:
l1=[1,2,3,4,5,False,"ekansh"]

In [7]:
a1=np.array([1,2,3],dtype='int64')

In [8]:
a1.dtype

dtype('int64')

In [9]:
a2=np.array(l1)

In [10]:
a2

array(['1', '2', '3', '4', '5', 'False', 'ekansh'], dtype='<U11')

In [11]:
a2.ndim

1

In [12]:
a2.shape

(7,)

In [8]:
a2=np.ones((3,3),dtype='int')

In [9]:
a2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [19]:
a3=np.zeros((3,4))

In [20]:
a3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
a3.size

12

In [22]:
a3.ndim

2

In [38]:
a3.shape

(3, 4)

In [30]:
a5=np.full((2,3,4),9)

In [31]:
a5.dtype

dtype('int32')

In [32]:
a5

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [56]:
a6 = np.random.random((4,5))

In [57]:
a6

array([[4.68808893e-01, 4.94392271e-01, 4.42308411e-01, 4.17844714e-01,
        1.47451492e-01],
       [6.99179264e-01, 6.95422635e-01, 5.77276636e-01, 2.53322539e-01,
        5.31246008e-01],
       [3.51466982e-01, 9.31831530e-02, 4.26067779e-01, 8.53613243e-01,
        8.72440512e-02],
       [1.50252187e-01, 7.26350925e-04, 2.46626739e-01, 3.63062257e-01,
        9.58992709e-01]])

In [23]:
?np.random.binomial

In [65]:
a7

5

In [69]:
np.random.normal(15,2,(1200))

array([16.59120508, 14.36803097, 18.19143967, ..., 17.63584544,
       10.78197799, 10.93416401])

In [2]:
a8=np.arange(0,100,25)

In [3]:
a8

array([ 0, 25, 50, 75])

In [81]:
a9=np.linspace(5,10,5)

In [82]:
a9

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [43]:
a8=np.arange(24)

In [44]:
a8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [45]:
a8.reshape((6,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
a8[0]

0

In [91]:
a1=np.array([1,2,3,4,5])

In [92]:
a1

array([1, 2, 3, 4, 5])

In [97]:
np.sum(a8)

276

In [47]:
a8=a8.reshape((2,3,4))

In [48]:
a8

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [116]:
np.sum(a8,axis=2)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [128]:
a8

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [125]:
np.sum(a8,axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [126]:
np.sum(a8,axis=(0,1))

array([60, 66, 72, 78])

In [127]:
np.sum(a8,axis=(0,2))

array([ 60,  92, 124])

In [155]:
np.sum(a8,axis=(2))

array([[ 6, 22, 38],
       [54, 70, 86]])

In [132]:
a1

array([1, 2, 3, 4, 5])

In [135]:
np.argmax(a1)

4

In [156]:
a8

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [157]:
a7

5

In [160]:
a8

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [163]:
a8=a8.reshape(6,4)

In [164]:
a8[2:5,1:3]

array([[ 9, 10],
       [13, 14],
       [17, 18]])

In [25]:
a10=a8.reshape(2,3,4)

In [26]:
a10

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
a10[0][2][1]

9

In [169]:
a10[:,2,1:3]

array([[ 9, 10],
       [21, 22]])

In [172]:
a8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [174]:
np.sum(a8,axis=0)

array([60, 66, 72, 78])

In [185]:
a20=np.random.random((2,3,4))
a21=np.random.random((2,4,4))

In [186]:
a20

array([[[0.16225989, 0.87368352, 0.75094591, 0.89809403],
        [0.24697919, 0.66574167, 0.98676747, 0.82753002],
        [0.60387129, 0.17000638, 0.9323049 , 0.69725093]],

       [[0.13453699, 0.91929123, 0.2802649 , 0.45504144],
        [0.75984143, 0.90191038, 0.94226334, 0.91520841],
        [0.51522451, 0.69069331, 0.22570963, 0.58465011]]])

In [187]:
a21

array([[[0.50027189, 0.83923422, 0.91802816, 0.35806451],
        [0.51621992, 0.19543944, 0.22041164, 0.09212307],
        [0.55366902, 0.35173535, 0.66846319, 0.58661273],
        [0.30043168, 0.88245166, 0.45944646, 0.19301182]],

       [[0.90250061, 0.67278114, 0.6460971 , 0.9311054 ],
        [0.61985905, 0.49968389, 0.64830425, 0.29728054],
        [0.29068204, 0.7585098 , 0.67038665, 0.29382464],
        [0.18461149, 0.74599983, 0.70713003, 0.8377074 ]]])

In [189]:
np.concatenate([a20,a21],axis=1)

array([[[0.16225989, 0.87368352, 0.75094591, 0.89809403],
        [0.24697919, 0.66574167, 0.98676747, 0.82753002],
        [0.60387129, 0.17000638, 0.9323049 , 0.69725093],
        [0.50027189, 0.83923422, 0.91802816, 0.35806451],
        [0.51621992, 0.19543944, 0.22041164, 0.09212307],
        [0.55366902, 0.35173535, 0.66846319, 0.58661273],
        [0.30043168, 0.88245166, 0.45944646, 0.19301182]],

       [[0.13453699, 0.91929123, 0.2802649 , 0.45504144],
        [0.75984143, 0.90191038, 0.94226334, 0.91520841],
        [0.51522451, 0.69069331, 0.22570963, 0.58465011],
        [0.90250061, 0.67278114, 0.6460971 , 0.9311054 ],
        [0.61985905, 0.49968389, 0.64830425, 0.29728054],
        [0.29068204, 0.7585098 , 0.67038665, 0.29382464],
        [0.18461149, 0.74599983, 0.70713003, 0.8377074 ]]])

In [192]:
np.hstack([a20,a21])

array([[[0.16225989, 0.87368352, 0.75094591, 0.89809403],
        [0.24697919, 0.66574167, 0.98676747, 0.82753002],
        [0.60387129, 0.17000638, 0.9323049 , 0.69725093],
        [0.50027189, 0.83923422, 0.91802816, 0.35806451],
        [0.51621992, 0.19543944, 0.22041164, 0.09212307],
        [0.55366902, 0.35173535, 0.66846319, 0.58661273],
        [0.30043168, 0.88245166, 0.45944646, 0.19301182]],

       [[0.13453699, 0.91929123, 0.2802649 , 0.45504144],
        [0.75984143, 0.90191038, 0.94226334, 0.91520841],
        [0.51522451, 0.69069331, 0.22570963, 0.58465011],
        [0.90250061, 0.67278114, 0.6460971 , 0.9311054 ],
        [0.61985905, 0.49968389, 0.64830425, 0.29728054],
        [0.29068204, 0.7585098 , 0.67038665, 0.29382464],
        [0.18461149, 0.74599983, 0.70713003, 0.8377074 ]]])

In [72]:
a1=np.arange(8207845)
a2=[None]*8207845
np.random.shuffle(a1)
for i in range(8207845):
    a2[i]=a1[i]

a2.index(1)


3180102

In [16]:
li=[1]
a=np.array(li)
a.ndim

1

In [80]:
a222=np.identity(3,dtype='int')
a222

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [88]:
a211=np.eye(3,dtype='int')
a211

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [96]:
x=np.random.randint(0,1001,50)
x

array([560, 325, 209,   8,  28, 475, 168, 466, 549, 903, 495, 553, 886,
       998, 933, 384, 118, 836, 797, 324, 183, 140, 755, 145, 642, 137,
       177, 831, 727,  96, 296, 523, 788, 550, 852, 641, 971, 943, 729,
        48, 634, 845, 780, 785, 985, 764, 453, 428, 722, 770])

In [111]:
print(x[49::-1])

[770 722 428 453 764 985 785 780 845 634  48 729 943 971 641 852 550 788
 523 296  96 727 831 177 137 642 145 755 140 183 324 797 836 118 384 933
 998 886 553 495 903 549 466 168 475  28   8 209 325 560]


In [144]:
x=np.array([1,2,3,4,5,0])

In [145]:
x

array([1, 2, 3, 4, 5, 0])

In [118]:
np.append(x,6)

array([1, 2, 3, 4, 5, 6])

In [121]:
np.insert(x,0,10)

array([10,  1,  2,  3,  4,  5])

In [125]:
np.insert(x,3,30)

array([ 1,  2,  3, 30,  4,  5])

In [138]:
x[4]=50
x

array([ 1,  2,  3,  4, 50])

In [139]:
def search_num(arr,num):
    for ele in arr:
        if ele==num:
            print("present")
            return
    print("not present")
    return
    

In [141]:
search_num(x,30)

not present


In [147]:
x.sort()

In [148]:
x

array([0, 1, 2, 3, 4, 5])

In [1]:
 import numpy as np

  a=np.array([9,8,7,1,3,1,2],ndim=3)

  a

IndentationError: unexpected indent (3834686391.py, line 3)

In [6]:
np.random.seed(10)

a = np.random.randint(10, size=10)

print(a)

[9 4 0 1 9 0 1 8 9 0]


In [7]:
print(a.argsort().argsort())

[7 5 0 3 8 1 4 6 9 2]
